In [1]:
import numpy as np

In [3]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
10 * np.ones((2,3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
np.random.random()

0.3853892914012935

In [8]:
np.random.random((2,3))

array([[0.02084462, 0.98626181, 0.06787546],
       [0.68399328, 0.7576143 , 0.134531  ]])

In [9]:
np.random.randn(2,3)

array([[ 0.00157117,  1.54129008, -0.26124499],
       [-0.64745521,  0.59222227, -1.05089085]])

In [12]:
R = np.random.randn(10000)

In [13]:
R.mean()

-0.0021066692907690844

In [14]:
np.mean(R)

-0.0021066692907690844

In [15]:
R.var()

0.9940635532923249

In [16]:
R.std()

0.9970273583469638

In [17]:
R = np.random.randn(10000, 3)

In [18]:
R.mean(axis=0)

array([0.01089759, 0.00603932, 0.0248086 ])

In [21]:
R.mean(axis=1)

(10000,)

In [22]:
R.mean(axis=1).shape

(10000,)

In [24]:
np.cov(R)

array([[ 0.10826698, -0.26071823, -0.21800487, ...,  0.08742347,
         0.01194086,  0.05707841],
       [-0.26071823,  1.03022959, -0.27567167, ...,  0.20876254,
        -0.15804931, -0.08956449],
       [-0.21800487, -0.27567167,  2.03204364, ..., -1.01030042,
         0.23321621, -0.21021274],
       ...,
       [ 0.08742347,  0.20876254, -1.01030042, ...,  0.50748405,
        -0.12508092,  0.09598651],
       [ 0.01194086, -0.15804931,  0.23321621, ..., -0.12508092,
         0.04286109, -0.00909131],
       [ 0.05707841, -0.08956449, -0.21021274, ...,  0.09598651,
        -0.00909131,  0.03579042]])

In [25]:
np.cov(R.T)

array([[ 1.01386363,  0.02654702,  0.01328307],
       [ 0.02654702,  1.02343523, -0.00865033],
       [ 0.01328307, -0.00865033,  0.98008564]])

In [26]:
np.cov(R, rowvar=False)

array([[ 1.01386363,  0.02654702,  0.01328307],
       [ 0.02654702,  1.02343523, -0.00865033],
       [ 0.01328307, -0.00865033,  0.98008564]])

In [28]:
np.random.randint(0, 10, size=(3,3))

array([[1, 7, 5],
       [8, 7, 2],
       [4, 4, 6]])

In [29]:
np.random.choice(10, size=(3,3))

array([[9, 7, 9],
       [2, 5, 4],
       [4, 3, 3]])