In [3]:
import numpy as np

In [2]:
L = [[1,2],[3,4]]
L

[[1, 2], [3, 4]]

In [6]:
L[0][1]

2

In [9]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [10]:
A[0,1]

2

In [12]:
A[:,0]

array([1, 3])

In [13]:
A.T # transpose -> flip rows and columns (switches row and column indices) through middle diagonal

array([[1, 3],
       [2, 4]])

In [14]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [16]:
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
A.dot(B) # matrix multiplication

array([[ 9, 12, 15],
       [19, 26, 33]])

In [19]:
A.dot(B.T)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [20]:
np.linalg.det(A)

-2.0000000000000004

In [21]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [22]:
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [23]:
np.trace(A)

5

In [24]:
np.diag(A)

array([1, 4])

In [25]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

In [26]:
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [27]:
Lam, V = np.linalg.eig(A)

In [28]:
V[:,0] * Lam[0] == A.dot(V[:,0])

array([ True, False])